services:   
  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cm:${VERSION:-latest}
    build:
      context: ./build/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-cm:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}sitecore-spe-assets:${SPE_VERSION}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}sitecore-sxa-xm1-assets:${SXA_VERSION}
        CLI_IMAGE: ${SITECORE_MODULE_REGISTRY}sitecore-management-services-xp1-assets:${CLI_VERSION}    
      dockerfile: Dockerfile
    mem_limit: 4g
    volumes:
      - ${LOCAL_DEPLOY_PATH:-.\deploy}\cm\website:C:\deploy      
    environment:
      SITECORE_DEVELOPMENT_PATCHES: ${CustomErrors:-Off}
    entrypoint: powershell -Command "& C:\\tools\\entrypoints\\iis\\Development.ps1"     
 
  solr-init:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-solr-init:${VERSION:-latest}
    build:
      context: ./build/solr-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-solr-init:${SITECORE_VERSION}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}sitecore-sxa-xm1-assets:${SXA_VERSION}

     
  cd:
    scale: 0